name: CI

on: [push]

env:
  CI: true

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install Windows spellchecking language packs
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Add-WindowsCapability -Online -Name Language.Spellchecking~~~de-DE~0.0.1.0
          Add-WindowsCapability -Online -Name Language.Spellchecking~~~fr-FR~0.0.1.0
      - name: Install Windows language packs
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Install-Language de-DE
          Install-Language fr-FR
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
